### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by nathansizemore** [ladislas/Bare-Arduino-Project#11]
The README lists the project under the MIT license, but the LICENSE file is GPL.  Can you clarify which sections of the project are licensed under which?

**Comment by ladislas** [comment]
yeah there is definitely something wrong with the licence. I'll review the issue and come back to you :)

**Comment by ladislas** [comment]
@nathansizemore changed the license to MIT.

please note that the Arduino software and Arduino-Makefile are both released under the LGPL license.
