### ISSUE TITLE
Arduino-Makefile submodule unable to checkout

### ISSUE THREAD

**Issue by cgel** [ladislas/Bare-Arduino-Project#12]
i follow the instructions in INSTALL.md and when using the command:
git submodule update --init --recursive
i get:
fatal: reference is not a tree: d1ea8699a49962f7c58beeaa25878755e0910195
Unable to checkout 'd1ea8699a49962f7c58beeaa25878755e0910195' in submodule path 'Arduino-Makefile'

**Comment by ladislas** [comment]
I get the same error, will fix this asap :)

**Comment by ladislas** [comment]
@cgel should work now.

tell me if everything is OK :)

**Comment by cgel** [comment]
the submodule update works great :)
But when i tried to compile BarProject the compiler does not have the path to my libs/ 
The USER_LIB_PATH is well defined.

**Comment by ladislas** [comment]
can you open a new issue and copy past the output of `make` please :)
