### ISSUE TITLE
feedback makefile for 1.6.3

### ISSUE THREAD

**Issue by kautzz** [ladislas/Bare-Arduino-Project#15]
Hey @ladislas ,

just tested your updates. Looking good so far.
After I added a few lines building went all good, code is running fine.
```
ARDUINO_VAR_PATH = /home/ubuntu/sketchbook/hardware/plantsandmachines/avr/variants
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
BOARDS_TXT = /home/ubuntu/sketchbook/hardware/plantsandmachines/avr/boards.txt
```
Somehow the core path was calculated wrong... there was a / to much.
Good job!

**Comment by ladislas** [comment]
Glad it's working! :)

> Somehow the core path was calculated wrong... there was a / to much.

Yes I've noticed that it sometimes happens, but it's not an issue for me. I'll do some testing.
