### ISSUE TITLE
YouCompleteMe not properly using Teensy/Teensyduino headers

### ISSUE THREAD

**Issue by alexozer** [ladislas/Bare-Arduino-Project#19]
I'm trying to set up YouCompleteMe (ycm) in Vim to autocomplete and error-detect code for Teensy 3.1. I installed Arduino 1.0.6 to a separate directory (because Bare-Arduino-Project doesn't support Arduino 1.6.* for Teensy), and installed Teensyduino to it. Then, I pointed ycm to this Arduino directory via .ycm_extra_conf.py:
```python
ArduinoLibDir = [
  "/home/alex/build/arduino-1.0.6" # location of Arduino patched with Teensyduino
  ,"/Applications/Arduino.app/Contents/Resources/Java/libraries"
  ,"/Applications/Arduino.app/Contents/Java/libraries"
  ,"/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries"
]
```
When using this test code:
```c++
#include <Arduino.h>

constexpr int pin = 13;

int main() {
	pinMode(pin, OUTPUT);
	digitalWrite(pin, HIGH);
	delay(1000);

	Serial.begin(9600);
	Serial.println("There, I turned on the LED, see?");
}
```
ycm throws no errors with pinMode(), digitalWrite(), and delay(), indicating it found them in Arduino.h just fine, but it doesn't recognize the Serial object:
![screenshot_2015-07-10_13-21-09](https://cloud.githubusercontent.com/assets/2074322/8624534/900ce67c-2706-11e5-9e91-ad60cbef896b.png)

Yet strangely, if I pretend I'm writing code for an original Arduino by changing the ycm library path to an unpatched Arduino directory:
```python
ArduinoLibDir = [
  "/usr/share/arduino" # unpatched arduino
  ,"/Applications/Arduino.app/Contents/Resources/Java/libraries"
  ,"/Applications/Arduino.app/Contents/Java/libraries"
  ,"/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries"
]
```
ycm recognizes Serial and autocompletes it just fine.

So, this leads me to believe that there's something to be fixed with the supplied .ycm_extra_conf.py.

**Comment by ladislas** [comment]
>  (because Bare-Arduino-Project doesn't support Arduino 1.6.* for Teensy)

no it's because Arduino-Makefile doesn't support the Teensy. There is a lot of changes going on in the way the Arduino IDE works and on how to parse the `board.txt` and so on. Until everyone is settled down, you have to use the `v1.0.6` for the teensy to work correctly with the `Makefile`

I'm going to try and find a solution.

For the moment, as the Teensy uses all the same functions as Arduino, you can debug your code with the unpatched version :)

**Comment by alexozer** [comment]
Agh, alright, I'll just deal with it.

**Comment by tiagoboldt** [comment]
Hey guys, afaik, this is still an issue today. @ladislas any reason to close it?

**Comment by alexozer** [comment]
TBH there's better ways to get completion nowadays, like with platformio for vscode.

**Comment by ladislas** [comment]
@tiagoboldt I don't use the teensy anymore. I don't have much time to investigate but I'd be happy to review any pull request.

I guess it's just about tweaking the ycm config :)
