### ISSUE TITLE
MONITOR_PORT does not support network connections

### ISSUE THREAD

**Issue by Ulli2k** [ladislas/Bare-Arduino-Project#20]
I want to execute the following flash command with your make file
avrdude -b 115200 -p m328p -c arduino -P net:beagle:4000 -Uflash:w:file.hex

But MONITOR_PORT does not support net:beagle:4000!

I additionally want to use make monitor with a different port "net:beagle:4001"

Would it be possible to include that or is there a workaround?

**Comment by ladislas** [comment]
hi @Ulli2k -- as the same issue is discussed [here](https://github.com/sudar/Arduino-Makefile/issues/378), I'm closing the issue now.
