### ISSUE TITLE
Could this work with Intel Galileo?

### ISSUE THREAD

**Issue by afrankenthal** [ladislas/Bare-Arduino-Project#27]
Hi, do you think this could work with Intel Galileo, which provides an Arduino environment? I absolutely despise the Arduino IDE and it would be nice to use this package instead. Thanks!

**Comment by ladislas** [comment]
I don't know, I haven't tried it.

If it works with just https://github.com/sudar/Arduino-Makefile, it will work with Bare Arduino Project.
