### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by ladislas** [ladislas/Bare-Arduino-Project#29]

**Comment by jvalskis** [comment]
Hi, ladislas, I picked up this project yesterday and my goal is to have it build for ATtiny85. But I encountered an exact same issue with that your travis build is failing on. 
Have you had any chance to investigate the cause for it?

**Comment by jvalskis** [comment]
OK, in my case it appears to have been avr-gcc version mismatch. The makefile was using 4.8.2 which was available in the system, instead of the 4.9.2 that comes with arduino. I set AVR_TOOLS_DIR to point to arduino installation tool directory (/hardware/tools/avr). This fixed my problem.

**Comment by ladislas** [comment]
thanks a lot @jvalskis. I'll look into that when I get time :)
