### ISSUE TITLE
Can't include anything from STL.

### ISSUE THREAD

**Issue by naccib** [ladislas/Bare-Arduino-Project#31]
Hey, I don't know if this is the better way yo contact you, but, here is my issue:
I can't include any header file from the STL:

If I try to include _vector_, this is what happens:
`FooProject.cpp:3:18: fatal error: vector: No such file or directory
 #include <vector>
`

How can I fix this?

**Comment by ladislas** [comment]
> How can I fix this?

you can't \-\- Arduino and avr don't support STL.

if you google "arduino stl" or "avr stl" you will find partial ports of STL, but I'm not sure I've ever seen vectors being porte on avr.
