### ISSUE TITLE
Uploading first example

### ISSUE THREAD

**Issue by Meresmata** [ladislas/Bare-Arduino-Project#36]
Hi,

 I tried out the project for the first time and tried out to upload the fooproject onto UnoR3 with a XUBUNTU 16.4.

I got no error while making, but error:2 while trying to upload

Settings were: 

PROJECT_DIR = /home/{user}/programmierung/MyArduinoProjects
BOARD_TAG  = uno
BOARD_SUB = atmega328p
AVRRDUDE = /usr/bin/avrdude
MONITOR_PORT = /dev/ttyACM0

> make[1]: Verzeichnis „/home/{user}/programmierung/MyArduinoProjects/src/FooProject“ wird betreten
/usr/bin/avrdude -q -V -p atmega328p -C /usr/../avrdude.conf -D -c arduino -b 115200 -P /dev/ttyACM0 \
		-U flash:w:/home/{user}/programmierung/MyArduinoProjects/bin/FooProject/uno/FooProject.hex:i
avrdude: can't open config file "/usr/../avrdude.conf": No such file or directory
avrdude: error reading system wide configuration file "/usr/../avrdude.conf"
/home/{user}/programmierung/MyArduinoProjects/Arduino-Makefile/Arduino.mk:1493: die Regel für Ziel „do_upload“ scheiterte
make[1]: *** [do_upload] Fehler 1
make[1]: Verzeichnis „/home/{user}/programmierung/MyArduinoProjects/src/FooProject“ wird verlassen
/home/{user}/programmierung/MyArduinoProjects/Arduino-Makefile/Arduino.mk:1485: die Regel für Ziel „upload“ scheiterte
make: *** [upload] Fehler 2

< Hi hope that it is readable, even though I am using German settings. ;)

I think, the problem is, that there is no "/usr/../avrdude.conf" calling avrdude -v  hints that System wide config is "/etc/avrdude.conf"

How, can the problem be solved?

**Comment by LucaTony** [comment]
I had the same problem. Just add `AVRDUDE_CONF      = /etc/avrdude.conf` to the Makefile

**Comment by ladislas** [comment]
@LucaTony thanks for the help

@Meresmata can you close if it solves your issue?

**Comment by pip010** [comment]
maybe add this to the example of the linux makefile?
### AVRDDUDE CONFIG
### Path to avrdude config directory.
AVRDUDE_CONF = /etc/avrdude.conf
