### ISSUE TITLE
libraries import

### ISSUE THREAD

**Issue by clement91190** [ladislas/Bare-Arduino-Project#44]
Hi, 

I'm trying to import the [ros_lib libraries](http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup). It seems the libraries import works only if the name of the header is the name of the folder (ie the name of the lib). Is there a fix for this ?

**Comment by ladislas** [comment]
> It seems the libraries import works only if the name of the header is the name of the folder (ie the name of the lib)

yes, that's how it works

> Is there a fix for this?

besides renaming the things, no. you can also use a main header with the name of the folder where you include everything else, as explained here: https://github.com/ladislas/Bare-Arduino-Project/issues/34#issuecomment-275864903
