### ISSUE TITLE
avr-g++ not linking to c++ libraries?

### ISSUE THREAD

**Issue by ghost** [ladislas/Bare-Arduino-Project#7]
I almost have it working with my toolchain (I'm on Linux mint 64bit). Except if I include std c++ libaries such as <array> in the top level *.ino file, the avr-g++ compiler cannot understand to link to the c++ files in usr/include/c++/. Hardcoding an include path is not really an option due to the recursive nature of the c++ libraries. The g++ compiler works fine recognizing these libs. I've tested with both g++ 4.8 and 4.9.

My error looks likes this: fatal error: array: No such file or directory  #include '<'array'>'

**Comment by jepperaskdk** [comment]
Did you get this to work? :-)
